# Generated by Django 4.2.7 on 2023-11-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('content', models.TextField(verbose_name='содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='изображение')),
                ('create_date', models.DateTimeField(verbose_name='дата создания')),
                ('is_public', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
