# Generated by Django 4.2.7 on 2023-11-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
