# Generated by Django 4.2.7 on 2023-12-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер версии'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('number', 'product'), name='unique_number_version_for_product'),
        ),
    ]
